set_property SRC_FILE_INFO {cfile:C:/Users/atomi/GitHub/hw-viv/div_archive/div32p2check/div32p2check.srcs/constrs_1/new/ioport.xdc rfile:../../../../div32p2check/div32p2check.srcs/constrs_1/new/ioport.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H5    IOSTANDARD LVCMOS33 } [get_ports { led0 }]; #IO_L24N_T3_35 Sch=led[4]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J5    IOSTANDARD LVCMOS33 } [get_ports { led1 }]; #IO_25_35 Sch=led[5]
