@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Jun 05 20:32:08 +0900 2024
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim test_divider_p2_time_impl -key {Post-Implementation:sim_1:Timing:test_divider_p2} -tclbatch test_divider_p2.tcl -protoinst "protoinst_files/design_1.protoinst" -view C:/Users/atomi/GitHub/hw-viv/div_archive/div32p2check/test_divider_p2_behav.wcfg -log simulate.log"
call xsim  test_divider_p2_time_impl -key {Post-Implementation:sim_1:Timing:test_divider_p2} -tclbatch test_divider_p2.tcl -protoinst "protoinst_files/design_1.protoinst" -view C:/Users/atomi/GitHub/hw-viv/div_archive/div32p2check/test_divider_p2_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
